package:
  name: libdiffpy
  ## Use __conda_version__.txt.
  # version: 1.2.77

source:
  # git_url: https://github.com/diffpy/libdiffpy.git
  git_url: ..

build:
  number: 0
  binary_relocation: False      # [linux]

requirements:
  build:
    - scons
    - boost 1.57.0              # [linux]
    - boost 1.56.0 py27_2       # [osx]
    - gsl
    - cxxtest
    - libobjcryst <2.0

  run:
    - boost 1.57.0              # [linux]
      # When package version includes build tag, its dependencies must be
      # listed as well.  https://github.com/conda/conda-build/issues/563
    - boost 1.56.0 py27_2       # [osx]
    -   python                  # [osx]
    -   bzip2 1.0.*             # [osx]
    -   zlib 1.2.*              # [osx]
    - gsl
    - libobjcryst <2.0

test:
  requires:
    - scons

  commands:
    # Run unit-test program with the installed shared library.
    # Make sure tests cannot use library file from the source directory.
    - scons -C "$SRC_DIR" --clean lib
    - export LD_LIBRARY_PATH="${PREFIX}/lib"                    # [linux]
    - export DYLD_FALLBACK_LIBRARY_PATH="${PREFIX}/lib"         # [osx]
    - ALLTESTSFAST=$(ls -t ${SRC_DIR}/build/fast*/tests/alltests | head -1)
    - "${ALLTESTSFAST}"

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
