package:
  name: libdiffpy
  ## Use __conda_version__.txt.
  # version: 1.2.77

source:
  # git_url: https://github.com/diffpy/libdiffpy.git
  git_url: ..

build:
  number: 0
  binary_relocation: False      # [linux]

requirements:
  build:
    - scons
    - boost                     # [linux]
    - boost 1.56.0 py27_2       # [osx]
    - gsl
    - cxxtest
    - libobjcryst

  run:
    - boost                     # [linux]
    - boost 1.56.0              # [osx]
    - gsl
    - libobjcryst

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
