{% set setupdata = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: libdiffpy
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/libdiffpy.git
  git_url: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - scons
  host:
    - libboost 1.67.0
    # Make sure this resolves to gsl from the diffpy channel.
    # Stock gsl=2.2.1=0 depends on libgcc package which on
    # Mac OS X shadows C++ system library with its own
    # incompatible version.
    - gsl 2.1
    #
    - libobjcryst >=2017.1.1

  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - libboost 1.67.0
    # Make sure this resolves to gsl from the diffpy channel.
    - gsl >=2.1

test:
  requires:
    - {{ compiler('cxx') }}
    - cxxtest
    - scons

  source_files:
    - SConstruct
    - site_scons/
    - src/SConscript
    - src/SConscript.configure
    - src/tests/

  # commands:
    # Execute the run_test.sh script.

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt
